### PR TITLE
fix: update broken links in migrate.py (#33)

### PR DESCRIPTION
**Pull request by kedras**

### CODE REVIEW

**Comment by adikhoff** [comment]
godotengine changed to redot-engine in github.

**Comment by kedras** [comment]
> godotengine changed to redot-engine in github.

Sorry, not sure I understand your comment. There are still broken links in docs due to repo name being "redot" instead of "redot-engine"....did the change broke something else? just to see what I've missed

**Comment by kedras** [comment]
https://github.com/Redot-Engine/redot-docs/pull/38

**Comment by adikhoff** [comment]
You may have a point

**Pull request merged**
