### PR TITLE
Rename files, internal links, external links. Still incomplete but should cover 98% of docs.

### PR DESCRIPTION
**Pull request by adikhoff**
PLEASE NOTE THIS IS A WORK IN PROGRESS

Main change is `migrate.py`.

* Creates a directory _migrated where the converted files go.
* Automatically searches, replaces strings in all rst files. Then copies them to _migrated
* Copies static assets that were manually edited to _migrated.
* For local builds, use `sphinx-build -b html ./_migrated/ _build/html`
* Github workflows edited to support the new setup

In the future, the goal is to replace the original rst files with the converted ones, making `migrate.py` irrelevant.

### CODE REVIEW

**Comment by adikhoff** [comment]
Test comment

**Review by Nicholai-Korea — APPROVED** [review]
Reviewed most of the file changes. Final approval waiting on Lead devs.

**Review by Salvakiya — APPROVED** [review]
Good work! We need to squash these commits though. some of the messages are not very descriptive.

**Comment by adikhoff** [comment]
> Good work! We need to squash these commits though. some of the messages are not very descriptive.

Yes I'll need to work on that. I've been developing solo lately so not very disciplined when it comes to commit messages. I will squash when I complete the PR.

**Review by Nicholai-Korea — APPROVED** [review]

**Comment by tindrew** [comment]
I'm going to review this, and then when you're back online ping me so we can get together and decide the path forward.

**Pull request closed without merging**
