### PR TITLE
Change all occurrences of godot to redot in documentation

### PR DESCRIPTION
**Pull request by fizzl**
Use provided _tools/redotify.sh to rename all occurrences of Godot to Redot, preserving case.
Rename all documentation files and images in same manner.

Passes CI and can be built.

### CODE REVIEW

**Comment by fizzl** [comment]
The MR is massive, because of the nature of the change. Heads up when going to Github "files changed"-page, might freeze your browser.

I suggest using offline tools for review.

**Comment by Starkium** [comment]
I appreciate the effort, but I'm seeing a lot of things that are renamed that should not be.

we need to be careful of copyright for one and for two we don't necessarily even want to copy what Godot did.
We're considering writing our own template and regenerating stuff. Among other things.

**Comment by fizzl** [comment]
Could you outline what should I avoid renaming? In general first, and then perhaps couple of examples so I understand the concerns. I'd like to contribute to the effort, and do it right.

Or perhaps direct me to a public issue to collaborate on, to avoid duplicate/wasted work? :)

**Comment by SkogiB** [comment]
Have to close this one for violation of the MIT license by accidentally stripping Godot's copyright notice. The changes here should end up coming in automatically after Craptain's update to the doc generation yml runs on Saturday.

**Comment by fizzl** [comment]
Fair! :)

**Pull request closed without merging**
